<a href="https://colab.research.google.com/github/komalborhade10/DNN/blob/master/DNN_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **MPL Classifier on Wine Dataset**

In [1]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv('Wine.csv',names=["Wine","Alcohol","Malic acid","Ash","Alcalinity of ash","Magnesium","Total phenols","Flavanoids","Nonflavanoid phenols","Proanthocyanins","Color intensity","Hue","OD280_OD315","Proline"])
df.head()

Wine  Alcohol  Malic acid   Ash  ...  Color intensity   Hue  OD280_OD315  Proline
0     1    14.23        1.71  2.43  ...             5.64  1.04         3.92     1065
1     1    13.20        1.78  2.14  ...             4.38  1.05         3.40     1050
2     1    13.16        2.36  2.67  ...             5.68  1.03         3.17     1185
3     1    14.37        1.95  2.50  ...             7.80  0.86         3.45     1480
4     1    13.24        2.59  2.87  ...             4.32  1.04         2.93      735

[5 rows x 14 columns]

In [8]:
y = df.iloc[:,0]
y

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: Wine, Length: 178, dtype: int64

In [10]:
X = df.iloc[:,1:]
X

Alcohol  Malic acid   Ash  ...   Hue  OD280_OD315  Proline
0      14.23        1.71  2.43  ...  1.04         3.92     1065
1      13.20        1.78  2.14  ...  1.05         3.40     1050
2      13.16        2.36  2.67  ...  1.03         3.17     1185
3      14.37        1.95  2.50  ...  0.86         3.45     1480
4      13.24        2.59  2.87  ...  1.04         2.93      735
..       ...         ...   ...  ...   ...          ...      ...
173    13.71        5.65  2.45  ...  0.64         1.74      740
174    13.40        3.91  2.48  ...  0.70         1.56      750
175    13.27        4.28  2.26  ...  0.59         1.56      835
176    13.17        2.59  2.37  ...  0.60         1.62      840
177    14.13        4.10  2.74  ...  0.61         1.60      560

[178 rows x 13 columns]

In [13]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=0.30,random_state=1)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
xtrain_transform = scaler.fit_transform(xtrain)
xtest_transform = scaler.fit_transform(xtest)


In [16]:
xtrain_transform[0:10]

array([[-1.10453814e+00, -5.30902019e-01, -1.36257411e-01,
        -3.74157304e-01, -1.29401378e+00, -1.01709571e+00,
        -4.44343803e-01,  1.26611962e+00,  1.59531634e-01,
        -1.07429532e+00,  5.16453506e-01, -4.18239705e-01,
        -8.51946601e-01],
       [-6.08848975e-01, -7.92239880e-01, -5.73220832e-01,
        -2.17309753e-01,  4.79360890e+00,  4.21716323e-01,
         3.31267647e-01, -4.03192799e-01,  2.94667537e+00,
        -9.90145976e-01,  8.56550345e-01,  7.60737827e-02,
         7.39761881e-01],
       [ 1.17054803e+00, -4.71890243e-01,  1.61159627e+00,
        -9.18317116e-02,  6.60037943e-01,  1.14112234e+00,
         1.03636897e+00,  1.41353068e-02,  3.63468980e-01,
        -1.90727201e-01,  1.23915929e+00,  1.13335541e+00,
         6.63136965e-01],
       [-1.37144769e+00,  1.55980087e+00,  1.18637918e-01,
         4.10080453e-01, -1.21885795e+00,  9.97241137e-01,
         1.09680622e+00, -1.32131463e+00,  2.31786855e+00,
        -9.05996632e-01, -8.86445954e

In [17]:
xtest_transform[0:10]

array([[ 0.67347647,  1.39903165,  0.56518381,  0.26682519,  0.24040779,
        -1.00181894, -1.71662457,  1.15658146, -1.74083082,  0.27216454,
         0.02378781, -1.34673321, -0.32499581],
       [-0.82464278, -0.51342186, -0.73117225,  0.96221903,  0.30435863,
        -0.71814534, -0.14547666, -0.05320835, -0.16304507, -1.51637007,
         0.49954396,  0.40416217, -1.24707459],
       [ 0.6144954 ,  1.21358161,  0.6392613 , -1.06833098,  0.81596535,
         0.44992238,  0.81980376, -1.33861002, -0.06565089, -0.09303363,
         0.02378781,  1.01851143,  0.12916239],
       [-1.07236328, -1.00022821, -2.36087702, -0.62327892,  3.05424475,
        -0.96844557, -0.97726084, -1.56544561,  1.57057136, -1.14648988,
         1.5462075 ,  0.57310822, -0.2204018 ],
       [ 0.76784619, -0.17729367,  1.08372623, -0.53983166,  0.75201451,
         0.95052284,  0.57334918,  0.32485097, -0.02669322,  0.46880971,
         0.83257327,  0.35808598,  1.58797359],
       [ 0.43755218,  1.781522

In [20]:
from sklearn.neural_network import MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(256,128,64,32),activation='relu',max_iter=300,solver='adam')
model.fit(xtrain_transform,ytrain)

MLPClassifier(hidden_layer_sizes=(256, 128, 64, 32), max_iter=300)

In [21]:
ypred = model.predict(xtest_transform)

In [22]:
from sklearn.metrics import accuracy_score,confusion_matrix
acc = accuracy_score(ytest,ypred)
print("Accuracy-",acc)

Accuracy- 1.0


In [25]:
cm =confusion_matrix(ytest,ypred)
print(cm)

[[23  0  0]
 [ 0 19  0]
 [ 0  0 12]]


In [26]:
from sklearn.metrics import classification_report
cr = classification_report(ytest,ypred)
print(cr)

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        23
           2       1.00      1.00      1.00        19
           3       1.00      1.00      1.00        12

    accuracy                           1.00        54
   macro avg       1.00      1.00      1.00        54
weighted avg       1.00      1.00      1.00        54

